on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_username: ${{ secrets.SNOWFLAKE_USER }}
      TF_VAR_password: ${{ secrets.SNOWFLAKE_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply Dev
        if: ${{ github.event.inputs.environment == 'dev' }}
        run: terraform apply -auto-approve -var-file="dev.tfvars"

      - name: Terraform Apply Prod
        if: ${{ github.event.inputs.environment == 'prod' }}
        run: terraform apply -auto-approve -var-file="prod.tfvars"